### ISSUE TITLE
An example usage would be great

### ISSUE THREAD

**Issue by srikanthkyatham** [noble-ai/rescript-cypress#1]
Hi

Thanks for the package, an example usage in tests would be great.
Again thanks for putting the package out. Good work

**Comment by AlexMoutonNoble** [comment]
Thanks for looking at it Srikanth
I'll add something next time I do a deploy, (or I'd love to see a PR of course.)
Really it looks just the same as youd think:

`cy->log("navigate_to_terms_of_service")`
